events_homepage:
  path:     /
  defaults: { _controller: EventsBundle:Default:index }

events_add:
  path:     /Add
  defaults: { _controller: EventsBundle:Default:Ajouter }
events_show:
  path:     /Afficher
  defaults: { _controller: EventsBundle:Default:index }

event_details:
  path:     /details/{id}
  defaults: { _controller: EventsBundle:Default:Details }
participer:
  path:     /participer/{id}
  defaults: { _controller: EventsBundle:Default:Participer }
Formulaire:
  path:     /Form
  defaults: { _controller: EventsBundle:Default:Formulaire }
edit_events:
  path:     /edit/{id}
  defaults: { _controller: EventsBundle:Default:edit }
delete_events:
  path:     /delete/{id}
  defaults: { _controller: EventsBundle:Default:delete }
